/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.text.View;

/**
 *
 * @author IvanA
 */
public class ComprobarIncidenciasView extends javax.swing.JFrame {

    public ComprobarIncidenciasView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Incidencias");
    }

    public JButton getBtn_agregarIncidencia() {
        return btn_agregarIncidencia;
    }

    public JButton getBtn_buscarIncidencia() {
        return btn_buscarIncidencia;
    }

    public JButton getBtn_eliminarIncidencia() {
        return btn_eliminarIncidencia;
    }

    public JButton getBtn_modificar_incidencia() {
        return btn_modificar_incidencia;
    }

    public JButton getBtn_volver_incidencia() {
        return btn_volver_incidencia;
    }

    public JComboBox<String> getCmb_filtro_incidencias() {
        return cmb_filtro_incidencias;
    }

    public JTable getTable_socios_incidencias() {
        return table_socios_incidencias;
    }

    public JTextField getTxt_espbusquedaIncidencia() {
        return txt_espbusquedaIncidencia;
    }

    public ButtonGroup getGroup_incidencia() {
        return group_incidencia;
    }

    public JRadioButton getRadio_grave() {
        return radio_grave;
    }

    public JRadioButton getRadio_leve() {
        return radio_leve;
    }

    public JRadioButton getRadio_ninguno() {
        return radio_ninguno;
    }
    
    
    
    

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_incidencia = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btn_agregarIncidencia = new javax.swing.JButton();
        btn_eliminarIncidencia = new javax.swing.JButton();
        cmb_filtro_incidencias = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_socios_incidencias = new javax.swing.JTable();
        btn_volver_incidencia = new javax.swing.JButton();
        txt_espbusquedaIncidencia = new javax.swing.JTextField();
        btn_buscarIncidencia = new javax.swing.JButton();
        btn_modificar_incidencia = new javax.swing.JButton();
        radio_leve = new javax.swing.JRadioButton();
        radio_grave = new javax.swing.JRadioButton();
        radio_ninguno = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Incidencias");

        btn_agregarIncidencia.setText("Agregar");
        btn_agregarIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarIncidenciaActionPerformed(evt);
            }
        });

        btn_eliminarIncidencia.setText("Eliminar");
        btn_eliminarIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarIncidenciaActionPerformed(evt);
            }
        });

        cmb_filtro_incidencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nombre", "Apellidos", "ID" }));
        cmb_filtro_incidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_filtro_incidenciasActionPerformed(evt);
            }
        });

        table_socios_incidencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idSocio", "nombre", "apellidos", "id_incidencia", "estado_incidencia", "tipo_incidencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_socios_incidencias);

        btn_volver_incidencia.setText("Volver");
        btn_volver_incidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volver_incidenciaActionPerformed(evt);
            }
        });

        btn_buscarIncidencia.setText("Buscar");

        btn_modificar_incidencia.setText("Modificar");
        btn_modificar_incidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar_incidenciaActionPerformed(evt);
            }
        });

        group_incidencia.add(radio_leve);
        radio_leve.setText("Leve");

        group_incidencia.add(radio_grave);
        radio_grave.setText("Grave");

        group_incidencia.add(radio_ninguno);
        radio_ninguno.setText("Ninguno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(btn_agregarIncidencia)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarIncidencia)
                .addGap(18, 18, 18)
                .addComponent(btn_modificar_incidencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(btn_volver_incidencia)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(txt_espbusquedaIncidencia)
                .addGap(18, 18, 18)
                .addComponent(radio_ninguno)
                .addGap(18, 18, 18)
                .addComponent(radio_leve)
                .addGap(18, 18, 18)
                .addComponent(radio_grave)
                .addGap(26, 26, 26)
                .addComponent(cmb_filtro_incidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscarIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_filtro_incidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_espbusquedaIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarIncidencia)
                    .addComponent(radio_grave)
                    .addComponent(radio_leve)
                    .addComponent(jLabel1)
                    .addComponent(radio_ninguno))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_modificar_incidencia)
                        .addComponent(btn_eliminarIncidencia)
                        .addComponent(btn_volver_incidencia))
                    .addComponent(btn_agregarIncidencia))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarIncidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarIncidenciaActionPerformed

    private void btn_eliminarIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarIncidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarIncidenciaActionPerformed

    private void cmb_filtro_incidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_filtro_incidenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_filtro_incidenciasActionPerformed

    private void btn_volver_incidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volver_incidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_volver_incidenciaActionPerformed

    private void btn_modificar_incidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar_incidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificar_incidenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprobarIncidenciasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprobarIncidenciasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprobarIncidenciasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprobarIncidenciasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprobarIncidenciasView().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarIncidencia;
    private javax.swing.JButton btn_buscarIncidencia;
    private javax.swing.JButton btn_eliminarIncidencia;
    private javax.swing.JButton btn_modificar_incidencia;
    private javax.swing.JButton btn_volver_incidencia;
    private javax.swing.JComboBox<String> cmb_filtro_incidencias;
    private javax.swing.ButtonGroup group_incidencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radio_grave;
    private javax.swing.JRadioButton radio_leve;
    private javax.swing.JRadioButton radio_ninguno;
    private javax.swing.JTable table_socios_incidencias;
    private javax.swing.JTextField txt_espbusquedaIncidencia;
    // End of variables declaration//GEN-END:variables
}
