/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author IvanA
 */
public class SocioView extends javax.swing.JFrame {

    /**
     * Creates new form SocioView
     */
    public SocioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_modificar_Socio = new javax.swing.JButton();
        txt_espbusquedaLibro = new javax.swing.JTextField();
        btn_buscar_socio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_agregarSocio = new javax.swing.JButton();
        btn_eliminarSocio = new javax.swing.JButton();
        cmb_filtro_socio = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_socios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_modificar_Socio.setText("Modificar");
        btn_modificar_Socio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar_SocioActionPerformed(evt);
            }
        });

        txt_espbusquedaLibro.setText("Introducir dni socio");

        btn_buscar_socio.setText("Buscar");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Socios");

        btn_agregarSocio.setText("Agregar");
        btn_agregarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarSocioActionPerformed(evt);
            }
        });

        btn_eliminarSocio.setText("Eliminar");
        btn_eliminarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarSocioActionPerformed(evt);
            }
        });

        cmb_filtro_socio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "idSocio", "nombre", "apellido", "correo", "telefono", "direccion", "id_incidencia", "dni" }));
        cmb_filtro_socio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_filtro_socioActionPerformed(evt);
            }
        });

        table_socios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idSocio", "nombre", "apellido", "telefono", "direccion", "id_incidencia", "dni"
            }
        ));
        jScrollPane2.setViewportView(table_socios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(txt_espbusquedaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(cmb_filtro_socio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_buscar_socio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(btn_agregarSocio)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarSocio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_modificar_Socio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_filtro_socio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_espbusquedaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_socio))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarSocio)
                    .addComponent(btn_eliminarSocio)
                    .addComponent(btn_modificar_Socio))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificar_SocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar_SocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificar_SocioActionPerformed

    private void btn_agregarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarSocioActionPerformed

    private void btn_eliminarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarSocioActionPerformed

    private void cmb_filtro_socioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_filtro_socioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_filtro_socioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocioView().setVisible(true);
            }
        });
    }

    public JButton getBtn_agregarSocio() {
        return btn_agregarSocio;
    }

    public JButton getBtn_buscar_socio() {
        return btn_buscar_socio;
    }

    public JButton getBtn_eliminarSocio() {
        return btn_eliminarSocio;
    }

    public JButton getBtn_modificar_Socio() {
        return btn_modificar_Socio;
    }

    public JComboBox<String> getCmb_filtro_socio() {
        return cmb_filtro_socio;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JTable getTable_socios() {
        return table_socios;
    }

   

    public JTextField getTxt_espbusquedaLibro() {
        return txt_espbusquedaLibro;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarSocio;
    private javax.swing.JButton btn_buscar_socio;
    private javax.swing.JButton btn_eliminarSocio;
    private javax.swing.JButton btn_modificar_Socio;
    private javax.swing.JComboBox<String> cmb_filtro_socio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_socios;
    private javax.swing.JTextField txt_espbusquedaLibro;
    // End of variables declaration//GEN-END:variables
}
